### ISSUE TITLE
Uncaught exception - Invalid field access : DefaultEditor

### ISSUE THREAD

**Issue by Patys** [HaxeFlixel/flixel-tools#44] opened 2015-01-21 17:21 UTC
Hi, I try to install flixel-tools and i've got:

 [0] Sublime Text
 [1] Flash Develop
 [2] Intellij Idea
 [3] None

Choose your default IDE.

3
Error detecting path of your haxelib flixel-tools.

 Your current settings:

Called from ? line 1
Called from FlxTools.hx line 174
Called from FlxTools.hx line 19
Called from FlxTools.hx line 122
Called from massive/sys/cmd/CommandLineRunner.hx line 109
Called from massive/sys/cmd/CommandLineRunner.hx line 258
Called from commands/SetupCommand.hx line 31
Called from commands/SetupCommand.hx line 240
Uncaught exception - Invalid field access : DefaultEditor

With anothers numbers is the same.

**Comment by Gama11** [comment] 2015-06-25 20:07
This shouldn't happen as long as there's a `settings.json` present, and the tools come with one by default.
Closing as I can't reproduce it.

**Closed by Gama11** 2015-06-25 20:07 UTC
