### ISSUE TITLE
Setup error when haxelib not in default directory: Ubuntu and Archlinux

### ISSUE THREAD

**Issue by paulorobertocruz** [HaxeFlixel/flixel-tools#67] opened 2016-09-16 17:20 UTC
I have the same problem over and over when running flixel-tools setup. The problem occurs in the part where the "flixel" cmd is installed.

I think that this issue may be related to issue #62

This is my output:
$ haxelib run flixel-tools setup

Do you want to set up the command alias 'flixel' to 'haxelib run flixel-tools'?
A simple flixel script will be added to your /usr/bin/ [y/n]?
y
[sudo] senha para paulorobertocruz: 
cp: não foi possível criar arquivo comum '/usr/lib/haxe/flixel': Arquivo ou diretório não encontrado
chmod: não é possível acessar '/usr/lib/haxe/flixel': Arquivo ou diretório não encontrado
ln: failed to create symbolic link '/usr/bin/flixel': Arquivo existe

Choose your default IDE:

  [0] Sublime Text
  [1] FlashDevelop
  [2] IntelliJ IDEA
  [3] Visual Studio Code
  [4] None

4

Your current settings:

Default Editor			: None
Auto open with IDE		: false

flixel-tools setup completed.
Try the 'flixel' command to test it! :)

##in case that is hard to understand the part in portuguese is:
cp: cannot create regular file ‘/usr/lib/haxe/flixel’: No such file or directory
chmod: cannot access ‘/usr/lib/haxe/flixel’: No such file or directory
ln: failed to create symbolic link ‘/usr/bin/flixel’: File exists

In the haxe.org/download/linux there is instalation code that puts haxelib in ~/haxelib and causes (i think) flixel-tools to fail flixel cmd instalation in machines that have not a default location for haxelib.

##Well the problem seams to be that the haxelib location is hardcoded in flixel-tools.
O made a fork of flixel-tools to try and resolve the issue. But anyone may beat me to the punch(XD)

var binPath = if (FileSys.isMac) "/usr/local/bin" else "/usr/bin";
var libPath = if (FileSys.isMac) "/usr/local/lib" else "/usr/lib";

**Comment by Gama11** [comment] 2016-09-16 17:36
This looks like a duplicate of #62?

Pull requests to fix this are welcome.

**Comment by paulorobertocruz** [comment] 2016-09-17 04:16
Mask as closed and move any active discussion to #62?

**Closed** 2016-09-17 07:54 UTC
